### PR TITLE
One fix and one work-around related to Sun Avoidance

### PR DESCRIPTION
**Pull request by mhasself**
- When assessing scan Sun safety, add a bit of a buffer in azimuth to account for turn-arounds.
- Don't consider multiple az branch options for each action -- behavior is buggy.

This is not intended for merge -- just for testing / temporary use.

@kmharrington I believe this will resolve the odd Sun Avoidance conflicts (and the weird indentation #73) encountered recently, but please check it for general good behavior.

### CODE REVIEW

**Comment by kmharrington** [comment]
Not totally enough.

Running with 
```
t0: 2024-07-12T18:00:00+00:00
t1: 2024-07-13T20:00:00+00:00
t0_state_file: None

elevation: 60
boresight: -45
az_speed: 0.5
az_accel: 1.0

hwp_dir: True
stow_at_end: True
run_relock: False
```
I'm getting:
```
Traceback (most recent call last):
  File "/so/home/kmharrin/software/scheduler-scripts/satp1/gen_schedule.py", line 122, in <module>
    main(**cfgs )
  File "/so/home/kmharrin/software/scheduler-scripts/satp1/gen_schedule.py", line 86, in main
    cmds, state = policy.seq2cmd(seq, t0, t1, return_state=True)
  File "/so/home/kmharrin/.local/lib/python3.10/site-packages/schedlib/policies/sat.py", line 711, in seq2cmd
    ops, state = build_op.apply(seq, t0, t1, state, self.operations)
  File "/so/home/kmharrin/.local/lib/python3.10/site-packages/schedlib/policies/stages/build_op.py", line 131, in apply
    ir = PlanMoves(**self.plan_moves).apply(ir)
  File "/so/home/kmharrin/.local/lib/python3.10/site-packages/schedlib/policies/stages/build_op.py", line 751, in apply
    moves = recur(pairs)
  File "/so/home/kmharrin/.local/lib/python3.10/site-packages/schedlib/policies/stages/build_op.py", line 730, in recur
    moves_rest = recur(cdr)
  File "/so/home/kmharrin/.local/lib/python3.10/site-packages/schedlib/policies/stages/build_op.py", line 730, in recur
    moves_rest = recur(cdr)
  File "/so/home/kmharrin/.local/lib/python3.10/site-packages/schedlib/policies/stages/build_op.py", line 730, in recur
    moves_rest = recur(cdr)
  [Previous line repeated 85 more times]
  File "/so/home/kmharrin/.local/lib/python3.10/site-packages/schedlib/policies/stages/build_op.py", line 747, in recur
    raise ValueError(f"no moves found between {b_prev} and {b_next}, very unusual!")
ValueError: no moves found between pre_block       (pre_bloc) az =   49.11: 24-07-13 17:25:13 -> 24-07-13 17:25:14 and NE. First choic (in_block) az =   49.11: 24-07-13 17:25:14 -> 24-07-13 18:00:00, very unusual!
```

**Comment by mhasself** [comment]
> Not totally enough.

I am thrilled that this seems to have activated another existing issue: #64 ... will take a look.

**Comment by kmharrington** [comment]
And if you want an example of the issue being related to planet scanning 
```
# yaml loads iso format automatically into datetimes
t0: 2024-07-14T20:00:00+00:00
t1: 2024-07-15T20:00:00+00:00
t0_state_file: None #state_files/state_2024-07-14T20:00:00+00:00.npy

elevation: 60
boresight: 0
az_speed: 0.5
az_accel: 1.0

hwp_dir: False
stow_at_end: False
run_relock: False

cal_targets:
  - source: saturn
    # boresight: # if not specified, use scan boresight
    elevation: 50
    focus: 'left'
    allow_partial: False
  - source: saturn
    # boresight: # if not specified, use scan boresight
    elevation: 50
    focus: 'right'
    allow_partial: False
```

**Comment by kmharrington** [comment]
It's the removal of the "branching" code that causes the crash. The buffer time is fine. 

the above config crashed at the current point in this branch. if I put the branching function back in then I get this at the end of the setting saturn scan. This still isn't correct because it's railing to the end of the Azimuth range. But more info. 
```
....
    run.seq.scan(
        description='saturn', 
        stop_time='2024-07-15T11:47:06.939945+00:00', 
        width=22.219, 
        az_drift=-0.00266, 
        subtype='cal',
        tag='saturn,setting,ws5,ws6',
    )
run.wait_until('2024-07-15T11:47:06.939945+00:00')
run.acu.move_to(az=395.0, el=50.0)
    run.smurf.bias_step(concurrent=True)
run.acu.move_to(az=395.0, el=50.0)
```

**Comment by kmharrington** [comment]
Found another error in move solving
```
# yaml loads iso format automatically into datetimes
t0: 2024-07-19T20:00:00+00:00
t1: 2024-07-20T20:00:00+00:00
t0_state_file: None #state_files/state_2024-07-19T20:00:00+00:00.npy

elevation: 60
boresight: -45
az_speed: 0.5
az_accel: 1.0

hwp_dir: False
stow_at_end: True
run_relock: True
```

**Comment by kmharrington** [comment]
in case it's different here's another 
```
# yaml loads iso format automatically into datetimes
t0: 2024-07-21T17:00:00+00:00
t1: 2024-07-22T17:00:00+00:00
t0_state_file: state_files/state_2024-07-21T17:00:00+00:00.npy

elevation: 60
boresight: 0
az_speed: 0.5
az_accel: 1.0

hwp_dir: True
stow_at_end: True
run_relock: False
```

**Comment by kmharrington** [comment]
Update, part of the issue may be that the master schedule file has a scan that we would not define as sun safe https://github.com/simonsobs/scheduler-scripts/blob/40eb88be488d25fe9ab26731b3e70f4f5109d4b9/satp1/master_files/cmb_2024_el60_20240423.txt#L3578

**Comment by kmharrington** [comment]
Now running on this branch https://github.com/simonsobs/scheduler-scripts/pull/2 to use a sun-safe master schedule. At least some of the issues described above still exist and I still see the telescope being sent to a non-sun safe position at the start of scans.

**Comment by kmharrington** [comment]
Not an instant emergency but I'm trying to plan the jupiter scans that start this week (8/1). the order of operations means we need to scan jupiter at az~400 to get back to CMB scanning after. I used the az_branch flag to get the jupiter scan to print out correctly but if can't solve the move between that and cmb scanning afterwards. 

using the updated sun branches in both scheduler and scheduler-scripts with this config: 
# yaml loads iso format automatically into datetimes
t0: 2024-08-01T17:00:00+00:00
t1: 2024-08-02T17:00:00+00:00
t0_state_file: 'state_files/state_2024-08-01T17:00:00+00:00.npy'

elevation: 60
boresight: 0
az_speed: 0.5
az_accel: 1.0

hwp_dir: False
stow_at_end: False
run_relock: False

cal_targets:
  - source: jupiter
    # boresight: # if not specified, use scan boresight
    elevation: 50
    focus: 'ws1'
    allow_partial: True
    az_branch: 375 ## need to scan one side of jupiter

**Comment by kmharrington** [comment]
hopefully not jinxing it, we've gone a week without hitting the sun, so we think this is ready to review/merge?

**Review by guanyilun — APPROVED** [review]

**Pull request merged**
