### PR TITLE
update hwp preamble

### PR DESCRIPTION
**Pull request by ykyohei**
Once both satp1 and satp3 deploy the hwp-supervisor agent, we can simplify the hwp preamble.
This PR will adress https://github.com/simonsobs/scheduler/issues/52

### CODE REVIEW

**Comment by bbixler500** [comment]
Looks good to me

**Review by guanyilun — APPROVED** [review]
looking good!

**Comment by kmharrington** [comment]
We need to coordinate implementing this change and deploying the supervisor agents on both machines

**Comment by ykyohei** [comment]
Bryce and I talked about the supervisor agent status yesterday.
It is deployed in both satp1 and satp3
For satp1, we should merge https://github.com/simonsobs/ocs-deployment-configs/pull/198, but docker agents are already running in daq-satp1 node.
@bbixler500 Correct me if something is wrong.

**Comment by bbixler500** [comment]
Yes that is correct Kyohei. The current satp1 schedule is already running using the supervisor agent with https://github.com/simonsobs/ocs-deployment-configs/pull/198 deployed to the daq-satp1 node (I manually changed the hwp function calls in the existing schedule).

**Comment by ykyohei** [comment]
Now the ocs-deployment-config https://github.com/simonsobs/ocs-deployment-configs/pull/198 is officially merged.
Let me proceed to merge this PR.

**Pull request merged**
