### PR TITLE
build_op: rewrap az when outside specified limits

### LINKED ISSUE #90: Moon scan runs into satp1 software prelimit for az CCW sector
I'm not sure this is a common fault in calibration obs or point source obs, but we had a surprise ACU agent alarm during a `generate_scan` command. The full schedule is here: https://site.simonsobs.org/schedules/satp1/2024-08-20T20%3A00%3A00%2B00%3A00_2024-08-21T20%3A00%3A00%2B00%3A00.py 

Relevant commands in block below:

```
  now = datetime.datetime.now(tz=UTC)
  scan_start = datetime.datetime(2024, 8, 21, 1, 54, 17, 884970, tzinfo=datetime.timezone.utc)
  scan_stop = datetime.datetime(2024, 8, 21, 4, 58, 40, 592471, tzinfo=datetime.timezone.utc)
  if now > scan_start:
      # adjust scan parameters
      az = 439.996 + -0.00423*(now-scan_start).total_seconds()
  else: 
      az = 439.996
  if now > scan_stop:
      # too late, don't scan
      pass
  else:
      run.acu.move_to(az, 50.0)

      print('Waiting until 2024-08-21 01:54:17.884970+00:00 to start scan')
      run.wait_until('2024-08-21T01:54:17.884970+00:00')

      run.seq.scan(
          description='moon', 
          stop_time='2024-08-21T04:58:40.592471+00:00', 
          width=28.157, 
          az_drift=-0.00423, 
          subtype='cal',
          tag='moon,rising,ws1,ws0,ws4',
      )
      run.smurf.bias_step(concurrent=True)
```

I'm not sure where the safe az range is specified in the `satp1.py` policy file on `simple-sun` branch, but it seems it may not be properly set. Our HW limits are -90 to 450, but we want to program a safe distance away from the software pre-limits, which define a narrower range. Let me know if these numbers are needed.

### PR DESCRIPTION
**Pull request by guanyilun**
fix #90

### CODE REVIEW

**Comment by kmharrington** [comment]
Ok question about this setup. Do the sun-safety checks happen after this un-wrapping? Right now it looks like it's quietly over-riding the az_branch setting for the example below. I'm happy it's found a safe scan but the original az-branch thoughts were for dodging to one side of the sun or the other and I'm seeing "solve sun safe moves" in before the "unwrapping" log messages.

`run_config.yaml`
```
platform: satp1

# yaml loads iso format automatically into datetimes
t0: 2024-08-20T20:00:00+00:00
t1: 2024-08-21T20:00:00+00:00
t0_state_file: None

elevation: 60
boresight: 0
az_speed: 0.5
az_accel: 1.0

# optional, only needed if running non-defaults
hwp_dir: True # True: forwards, False: backwards
home_at_end: True # Home: spin down HWP and go to (180,60)
run_relock: False # Relock detectors at the beginning of the schedule
no_cmb: False

cal_targets:
  - source: moon
    # boresight: # if not specified, use scan boresight
    elevation: 50
    focus: 'ws0,ws4,ws1'
    allow_partial: False
    az_branch: 270
  - source: jupiter
    # boresight: # if not specified, use scan boresight
    elevation: 48
    focus: 'ws1'
    allow_partial: True
    az_branch: 270 
```

```
2024-09-20 19:28:24,607 [INFO] ================ solve moves ================ 
2024-09-20 19:28:24,607 [INFO] step 1: solve sun-safe moves 
2024-09-20 19:28:24,607 [INFO] block az (439.9964870742548) outside limits, unwrapping... 
2024-09-20 19:28:24,607 [INFO] -> unwrapping az: 439.9964870742548 -> 79.99648707425479 
2024-09-20 19:28:24,607 [INFO] block az (439.9964870742548) outside limits, unwrapping... 
2024-09-20 19:28:24,607 [INFO] -> unwrapping az: 439.9964870742548 -> 79.99648707425479 
2024-09-20 19:28:24,607 [INFO] block az (439.9964870742548) outside limits, unwrapping... 
2024-09-20 19:28:24,607 [INFO] -> unwrapping az: 439.9964870742548 -> 79.99648707425479 
2024-09-20 19:28:25,156 [INFO] step 2: simplify moves 
2024-09-20 19:28:25,157 [INFO] simplify_moves: i_pass=0 
2024-09-20 19:28:25,157 [INFO] simplify_moves: IR converged 
2024-09-20 19:28:25,157 [INFO] ================ lowering (ops) ================ 
```

**Comment by guanyilun** [comment]
This rewrapping happens before actually solving for sun-safe moves, so I don't think it will cause new sun-safety problem.

**Review by kmharrington — APPROVED** [review]
I've now checked this we some previous weird sun-safety ones. So yes, good to merge.

**Comment by guanyilun** [comment]
Thanks!

**Pull request merged**
