### PR TITLE
Add elevation check and hwp spin down for move commands if elevation too low

### PR DESCRIPTION
**Pull request by mmccrackan**
Adjustments to try and address #128.

### CODE REVIEW

**Review by guanyilun — APPROVED** [review]
looks good to me!

**Review by kmharrington — CHANGES_REQUESTED** [review]
Generally looks good and I like the way it's implemented. One requested change, I'd like for the min_el in the per-sat configs instead of effectively hardcoded for all SATs. There's a decent chance it changes at least once in the future so might as well already set it up to be in the configs.

**Comment by kmharrington** [comment]
I should also say, I tested this on a bunch of satp2 schedules and it works as desired!

**Comment by mmccrackan** [comment]
> I should also say, I tested this on a bunch of satp2 schedules and it works as desired!

Okay, I've added `min_hwp_el` to the SAT policy configs.  I incorporated code from @guanyilun's dev branch to read the policies into the `build_ops` and `build_sched` classes to make it easier to pass things like the `min_hwp_el` and `max_cmb_duration` into them, so there are a few more changes here as well.

**Review by kmharrington — APPROVED** [review]
Looks great! I made a few minor changes and caught a missing parameter for satp3. Thanks for doing this so quickly!

**Pull request merged**
