### PR TITLE
Use new sorunlib timing utilities

### PR DESCRIPTION
**Pull request by BrianJKoopman**
_(This shouldn't be merged until those two upstream sorunlib PRs are merged, but this gets us ready to go. Will mark as draft for now, though comments welcome.)_

This uses the new features from https://github.com/simonsobs/sorunlib/pull/180 and https://github.com/simonsobs/sorunlib/pull/181 to replace the verbose checking of datetimes. Here are some diffs to illustrate:

**Normal scans:**
```diff
369,376c330,336
< scan_stop = datetime.datetime(2024, 8, 18, 19, 49, 59, 990000, tzinfo=datetime.timezone.utc)
< if datetime.datetime.now(tz=UTC) < scan_stop - datetime.timedelta(minutes=10):
<     run.seq.scan(
<         description='NE=2nd, 3rd or 4th choice',
<         stop_time='2024-08-18T19:49:59.990000+00:00',
<         width=40.0, az_drift=0,
<         subtype='cmb', tag='49-89',
<     )
---
> run.seq.scan(
>     description='NE=2nd, 3rd or 4th choice',
>     stop_time='2024-08-18T19:49:59.990000+00:00',
>     width=40.0, az_drift=0,
>     subtype='cmb', tag='49-89',
>     min_duration=600,
> )
```

**Source scans:**
```diff
226,251c204,220
< now = datetime.datetime.now(tz=UTC)
< scan_start = datetime.datetime(2024, 8, 18, 9, 7, 12, 802942, tzinfo=datetime.timezone.utc)
< scan_stop = datetime.datetime(2024, 8, 18, 11, 42, 56, 260894, tzinfo=datetime.timezone.utc)
< if now > scan_start:
<     # adjust scan parameters
<     az = 389.394 + -0.00495*(now-scan_start).total_seconds()
< else:
<     az = 389.394
< if now > scan_stop:
<     # too late, don't scan
<     pass
< else:
<     run.acu.move_to(az, 50.0)
<
<     print('Waiting until 2024-08-18 09:07:12.802942+00:00 to start scan')
<     run.wait_until('2024-08-18T09:07:12.802942+00:00')
<
<     run.seq.scan(
<         description='jupiter',
<         stop_time='2024-08-18T11:42:56.260894+00:00',
<         width=30.395,
<         az_drift=-0.00495,
<         subtype='cal',
<         tag='jupiter,rising,ws1,ws2',
<     )
<     run.smurf.bias_step(concurrent=True)
---
> run.acu.move_to_target(389.394, 50.0,
>     start_time='2024-08-18T09:07:12.802942+00:00',
>     stop_time='2024-08-18T11:42:56.260894+00:00',
>     drift=-0.00495)
>
> print('Waiting until 2024-08-18 09:07:12.802942+00:00 to start scan')
> run.wait_until('2024-08-18T09:07:12.802942+00:00')
>
> run.seq.scan(
>     description='jupiter',
>     stop_time='2024-08-18T11:42:56.260894+00:00',
>     width=30.395,
>     az_drift=-0.00495,
>     subtype='cal',
>     tag='jupiter,rising,ws1,ws2',
> )
> run.smurf.bias_step(concurrent=True)
```

**Imports/header:**
```diff
3d2
< import datetime
11d9
< UTC = datetime.timezone.utc
```

One thing to note, particularly on the source scans, is that this will now always run the `run.smurf.bias_step()` line, even if we end up skipping the actual scan, if `stop_time` has already passed.

This saved 40 lines in the quick test schedule I generated, but does a lot for readability in my opinion.

### CODE REVIEW

**Comment by BrianJKoopman** [comment]
This is deployed everywhere on site except for satp2, though it's ready to be updated when the next schedule gap occurs. I think it's good to review now.

**Review by kmharrington — COMMENTED** [review]
See https://github.com/simonsobs/scheduler/pull/126

**Comment by BrianJKoopman** [comment]
Alright, force pushing a rebase as requested.

**Review by kmharrington — APPROVED** [review]
Been using this for a while. Thanks!

**Pull request merged**
