### PR TITLE
allow passing in hwp cfg

### PR DESCRIPTION
**Pull request by guanyilun**

### CODE REVIEW

**Review by kmharrington — APPROVED** [review]
So for adding this to a config file it should end up looking something like this: 

```
config = {
    'blocks': blocks,
    'geometries': geometries,
    'rules': {
        'sun-avoidance': {
            'min_angle_az': 45,
            'min_angle_alt': 45,
        },
        'min-duration': {
            'min_duration': 600
        },
        'az-range': {
            'az_range': [-10, 400],
            'trim': True
        },
    },
    'allow_partial':False,
    'cal_targets': cal_targets,
    #'merge_order': ['moon', 'jupiter','saturn', 'baseline'],
    'merge_order': ['moon', 'baseline'],
    'time_costs': {
        'det_setup': 40*60,
        'bias_step': 60,
        'ufm_relock': 15*60,
        'hwp_spin_up': 20*60,
        'hwp_spin_down': 10*60,
    },
    'ufm_relock': True,
    'debug_mode': True,
    'scan_tag': None,
    'az_speed' : params.az_speed,
    'az_accel' : params.az_accel,
    'hwp_config': {
        'gripper' : 'hwp-gripper',
        'power-iboot-hwp-2' : 'iboot2',
        'hwp-pid' : 'pid',
        'hwp-pmx' : 'pmx'
    }
}
```

@samdayweiss  could you test this out?

**Comment by samdayweiss** [comment]
Awesome, this is great. Thank you @kmharrington @guanyilun!!

**Comment by guanyilun** [comment]
it by default spins up hwp. Adding an option to disable it is easy, but as I'm reworking the sat policy, maybe it's worth waiting for that

**Comment by guanyilun** [comment]
no longer relevant.

**Pull request closed without merging**
